[package]
name = "PFLeveler"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
PathFinder = { path = "../PathFinder" }
slint = "1.10.0"
rand = "0.9.0"

[build-dependencies]
slint-build = "1.10.0"
